mybatis-plus:
  mapper-locations:  classpath:mapper/*.xml
  global-config:
    banner:  off
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/fiction
    username:  root
    password:  root
  application:
    name: user-service
  data:
    redis:
      host:  127.0.0.1
      port:  6379
logging:
  level:
     com.thejianghuartist.mapper: debug